server:
  port: 10010
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10000/eureka
    register-with-eureka: false # 注册自己（默认true）

