spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: QAZ123qaz#
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
jpa:
  show-sql: true