#spring:
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    check-template-location: true
#    cache: false
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML5
#    servlet:
#      content-type: text/html

#端口
server:
  port: 8809

#国际化
spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
#    date-format: yyyy-MM-dd HH:mm